### PR TITLE
feat: add artifacts

### PR DESCRIPTION
**Pull request by tserg**
This PR adds the artifacts for core contracts deployed on mainnet.

### CODE REVIEW

**Review by milancermak — APPROVED** [review]
LGTM

**Comment by milancermak** [comment]
I'm wondering if we should also offer ABI files (just the `"abi"` section) since those would be the most interesting for integrators I think. Not sure what's the best practice here.

@kseikyo any thoughts?

**Comment by kseikyo** [comment]
> I'm wondering if we should also offer ABI files (just the `"abi"` section) since those would be the most interesting for integrators I think. Not sure what's the best practice here.

It's a nice addition. I think just a folder called abis with the files would work well, as it keeps things consistent and makes it easy to see when an ABI has changed.

The standard is to have a local copy in the project, but some projects have a repo dedicated to ABIs. I'm not sure we need that. If we reach a point where we have different versions, we can discuss how to handle them then.

**Comment by milancermak** [comment]
Cool, thanks for the input.

I ran `jq .abi` on all the artifact JSONs and stored the results in separate JSON files under `abis/`.

**Comment by tserg** [comment]
Should we move the full artifact files into a `contract_classes` folder? I think it looks better that way :smile:

**Comment by milancermak** [comment]
Yeah, good idea

**Pull request merged**
